# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  watcher_deploy:
    name: My first job
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: "checkout code" 
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/800709475320/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider"
          service_account: "github-actions@guild-helper-348715.iam.gserviceaccount.com"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: "hello-world-fn"
          runtime: "nodejs16"
          entry_point: "hey"
          source_dir: "./watcher"
          region: "europe-central2"

      # Example of using the output
      - id: "test"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
